### ISSUE TITLE
how to use these configs and what info does it extract

### ISSUE THREAD

**Issue by waleedsaud** [opennms-config-modules/oracle#1]
how to use these configs, because the readme doesn't explain to to implement this config and what it does monitor in oracle database.

**Comment by mfuhrmann** [comment]
Ugly response time here. Sorry about that. The Readme file gives some hints how to add the configs in OpenNMS.
On Oracle side there should be a SNMP trap configuration to send SNMP traps to a SNMP receiver. It's required to configure Oracle like this.

Also #2 was added to get some metrics out of Oracle.
